# Case Study Vorhersage Weinqualität

## 1. Daten einlesen

In [1]:
import pandas as pd
import numpy as np

In [2]:
White_wine_df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv", 
                            sep =";")

In [3]:
White_wine_df

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.0              0.27         0.36  ...       0.45      8.8        6
1               6.3              0.30         0.34  ...       0.49      9.5        6
2               8.1              0.28         0.40  ...       0.44     10.1        6
3               7.2              0.23         0.32  ...       0.40      9.9        6
4               7.2              0.23         0.32  ...       0.40      9.9        6
...             ...               ...          ...  ...        ...      ...      ...
4893            6.2              0.21         0.29  ...       0.50     11.2        6
4894            6.6              0.32         0.36  ...       0.46      9.6        5
4895            6.5              0.24         0.19  ...       0.46      9.4        6
4896            5.5              0.29         0.30  ...       0.38     12.8        7
4897            6.0              0.21         0.38  ...       0.32     11.8        6

[4898 rows x 12 columns]

In [4]:
White_wine_df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

Sowohl Spalten als auch Datentypen passen....also los gehts!

## 2. Daten aufbereiten für Machine Learning

In [5]:
# Label/ Zielgröße in y abspeichern
y = White_wine_df['quality']
X = White_wine_df.iloc[:, :-1]  # verkürzte Schreibweise: alle Zeilen (der Doppelpunkt vor dem Komma) und zu den Zeilen die jeweiligen Spalten bis hin zur vorletzten werden in X gespeichert.

# letzter Test. 
print("X hat folgenden Shape", X.shape) # X sollte 150 Zeilen mit jeweils 4 Spalten/ Features haben
print("y-Vektor hat folgenden Shape", y.shape) #Y sollte 150 Zeilen mit 1 Wert, der Zielvariablen haben

X hat folgenden Shape (4898, 11)
y-Vektor hat folgenden Shape (4898,)


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# Test ob Aufteilung funktioniert hat.
print("Shapes von X_train und X_test", X_train.shape, X_test.shape)
print("Shapes von y_train und y_test", y_train.shape, y_test.shape)

Shapes von X_train und X_test (3428, 11) (1470, 11)
Shapes von y_train und y_test (3428,) (1470,)


## 3. Machine Learning

In [7]:
from sklearn.metrics import mean_squared_error 
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import plot_confusion_matrix

def Model_accuracy(predicted_y_values, real_y_values):
  print(confusion_matrix(real_y_values, predicted_y_values)) #Confusion Matrix
  print(classification_report(real_y_values, predicted_y_values)) # Print summary report
  print('accuracy is ',accuracy_score(predicted_y_values, real_y_values)) # Print accuracy score

### 3.1 SVM

In [8]:
from sklearn import svm

SVC_basis = svm.SVC()
SVC_basis.fit(X_train, y_train)
y_pred_SVM_basis = SVC_basis.predict(X_test)

In [ ]:
Model_accuracy(y_pred_SVM_basis, y_test)

[[  0   0   1   8   0   0]
 [  0   0   1  59   0   0]
 [  0   0   5 453   0   0]
 [  0   0   2 628   0   0]
 [  0   0   0 267   0   0]
 [  0   0   0  46   0   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         9
           4       0.00      0.00      0.00        60
           5       0.56      0.01      0.02       458
           6       0.43      1.00      0.60       630
           7       0.00      0.00      0.00       267
           8       0.00      0.00      0.00        46

    accuracy                           0.43      1470
   macro avg       0.16      0.17      0.10      1470
weighted avg       0.36      0.43      0.26      1470

accuracy is  0.4306122448979592


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [9]:
from sklearn.ensemble import RandomForestClassifier

RandomForest_clf = RandomForestClassifier()
RandomForest_clf.fit(X_train, y_train)

y_pred_RandomForest = RandomForest_clf.predict(X_test)

In [10]:
Model_accuracy(y_pred_RandomForest, y_test)

[[  0   0   4   5   0   0]
 [  0   6  32  20   2   0]
 [  0   0 290 162   6   0]
 [  0   0  69 522  38   1]
 [  0   0   8 119 138   2]
 [  0   0   1  18  10  17]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         9
           4       1.00      0.10      0.18        60
           5       0.72      0.63      0.67       458
           6       0.62      0.83      0.71       630
           7       0.71      0.52      0.60       267
           8       0.85      0.37      0.52        46

    accuracy                           0.66      1470
   macro avg       0.65      0.41      0.45      1470
weighted avg       0.68      0.66      0.65      1470

accuracy is  0.6619047619047619


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### 3.2 Parameter tunen

Schauen Sie sich die Dokumentation zu den einzelnen Algorithmen genauer an: [Link](https://scikit-learn.org/stable/supervised_learning.html#supervised-learning).
Dort gibt es jeweils einen Abschnitt Parameter. Probieren Sie aus, wie sich die Ergebnisse des Algorithmus je nach Wahl der Parameter ändern

In [11]:
RandomForest_clf_tuned = RandomForestClassifier(n_estimators=200, max_depth=12, max_features=5)
RandomForest_clf_tuned.fit(X_train, y_train)

y_pred_RandomForest_tuned = RandomForest_clf_tuned.predict(X_test)

In [12]:
Model_accuracy(y_pred_RandomForest_tuned, y_test)

[[  0   0   4   5   0   0]
 [  0   5  32  22   1   0]
 [  0   0 279 174   5   0]
 [  0   0  74 520  36   0]
 [  0   0  10 132 125   0]
 [  0   0   1  20  12  13]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         9
           4       1.00      0.08      0.15        60
           5       0.70      0.61      0.65       458
           6       0.60      0.83      0.69       630
           7       0.70      0.47      0.56       267
           8       1.00      0.28      0.44        46

    accuracy                           0.64      1470
   macro avg       0.67      0.38      0.42      1470
weighted avg       0.67      0.64      0.62      1470

accuracy is  0.6408163265306123


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


###3.3 Nutzen Modell für Vorhersage eines anderen Weins

In [13]:
print(X_test.columns)

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')


In [14]:
test_wine =  [[1, # fixed acidity
               0, # volatile acidity
               17., # citric acid
               0, # residual sugar
               1, # chlorides
               150., # free sulfur dioxide
               223, # total sulfur dioxide
               222, # density
               333, # pH
               223, # sulphates
               333]] # alcohol
          

In [17]:
print("Der Testwein hat eine Qualität von {}".format(RandomForest_clf_tuned.predict(test_wine)))

Der Testwein hat eine Qualität von [6]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"
